# 服务器的配置项
server:
  port: 9192


#tcp服务配置
jichat:
  user:
      userId: 1747905091907751936
      userName: jisl
      password: 12345678
      version: 1.0
      deviceIdentifier: jpOKnf5vGaW9IcitjEPrUGINjDSSEvXd
      deviceName: iPhoneX
      deviceType: 1
      osType: 102


user:
  url: http://localhost:18081/user-api
chat:
  url: http://localhost:18080/chat-api