
spring:
  # Application 的配置项
  application:
    name: chat-client
  profiles:
    active: dev
  main:
    allow-circular-references: true



  # Swagger 配置项
swagger:
  title: JiChat 客户端-接口
  description: 客户端接口
  author: ji
  version: 1.0.0
  base-package: com.ji.jichat.client.controller

