# 服务器的配置项
server:
  port: 18081
  servlet:
    context-path: /user-api/
spring:
  # Application 的配置项
  application:
    name: user-service
  # Profile 的配置项
  profiles:
    active: dev

#  main:
#    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
#    allow-bean-definition-overriding: true # 允许 Bean 覆盖，例如说 Dubbo 或者 Feign 等会存在重复定义的服务

# MyBatis Plus 配置项
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag  # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

  mapper-locations: classpath:mapper/*.xml
  # 实体类扫描路径
  type-aliases-package: com.ji.jichat.user.entity

feign:
  client:
    config:
      default:
        #         // 设置连接超时时间和读取超时时间，单位为毫秒
        connectTimeout: 5000
        readTimeout: 15000



# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.ji.jichat.user
  default-flat-param-object: true


knife4j:
  enable: true # 2.2 是否开启 Swagger 文档的 Knife4j UI 界面
  setting:
    language: zh_cn

  # Swagger 配置项
swagger:
  title: JiChat User-接口
  description: User模块
  author: ji
  version: 1.0.0
  base-package: com.ji.jichat.user.controller




