spring:
  # 数据源配置项
  datasource:
    url: jdbc:mysql://192.168.137.179:3306/ji_chat_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        namespace: dev # Nacos 命名空间
        server-addr: 192.168.137.179:8848



  rabbitmq:
    host: 192.168.137.179
    port: 5672
    username: dream
    password: 123456

  redis:
    host: 192.168.137.179
    port: 6379
    password: 123456

