# 服务器的配置项
server:
  port: 18080
  servlet:
    context-path: /chat-api/
spring:
  # Application 的配置项
  application:
    name: chat-service
  # Profile 的配置项
  profiles:
    active: dev
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true

feign:
  client:
    config:
      default:
        #         // 设置连接超时时间和读取超时时间，单位为毫秒
        connectTimeout: 5000
        readTimeout: 15000


  # Swagger 配置项
swagger:
  title: JiChat Chat-接口
  description: 实现客户端和服务端连接功能
  author: ji
  version: 1.0.0
  base-package: com.ji.jichat.chat.controller


#tcp服务配置
tcpServer:
  tcpPort: 7066
  httpPort: ${server.port}
  bossThreadCount: 1
  # workerThreadCount: 4
  keepalive: true
  backlog: 32768

