# 服务器的配置项
server:
  port: 18080
  servlet:
    context-path: /chat-api/
spring:
  # Application 的配置项
  application:
    name: chat-service
  # Profile 的配置项
  profiles:
    active: dev
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true

  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
    allow-bean-definition-overriding: true # 允许 Bean 覆盖，例如说 Dubbo 或者 Feign 等会存在重复定义的服务

feign:
  client:
    config:
      default:
        #         // 设置连接超时时间和读取超时时间，单位为毫秒
        connectTimeout: 5000
        readTimeout: 15000



# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.ji.jichat.chat
  default-flat-param-object: true


knife4j:
  enable: true # 2.2 是否开启 Swagger 文档的 Knife4j UI 界面
  setting:
    language: zh_cn


  # Swagger 配置项
swagger:
  title: JiChat Chat-接口
  description: 实现客户端和服务端连接功能
  author: ji
  version: 1.0.0
  base-package: com.ji.jichat.chat.controller
  license: MIT License
  licenseUrl: https://opensource.org/license/mit

#tcp服务配置
tcpServer:
  tcpPort: 7066
  httpPort: ${server.port}
  bossThreadCount: 1
  # workerThreadCount: 4
  keepalive: true
  backlog: 32768

