spring:
  # 数据源配置项
  datasource:
    url: jdbc:mysql://localhost:3306/jimall_system?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        namespace: dev_1024 # Nacos 命名空间
        server-addr: 192.168.137.130:8848



  rabbitmq:
    host: 192.168.137.130
    port: 5672
    username: dream
    password: 123456



outside-ip: 192.168.77.130
inner-ip: 192.168.77.130