# 服务器的配置项
server:
  port: 18081
  servlet:
    context-path: /user-api/
spring:
  # Application 的配置项
  application:
    name: user-service
  # Profile 的配置项
  profiles:
    active: dev
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true

# MyBatis Plus 配置项
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: null # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      logic-delete-field: del_flag
  mapper-locations: classpath:mapper/*.xml
  # 实体类扫描路径
  type-aliases-package: com.ji.jichat.user.entity

  # Swagger 配置项
swagger:
  title: JiChat User-接口
  description: User模块
  author: ji
  version: 1.0.0
  base-package: com.ji.jichat.user.controller


